import { z } from "zod";

export const HealthCheckResponse = z.object({ status: z.string() });
export const ListPatentsResponse = z.any();
export const AnalyzePatentBody = z.any();
export const GetPatentParams = z.any();
export const DeletePatentParams = z.any();
export const GetPatentResponse = z.any();
export const SearchPatentsQueryParams = z.any();
export const SearchPatentsResponse = z.any();
export const GetPatentStatsResponse = z.any();
export const FormalityCheckBody = z.any();
export const FormalityCheckResponse = z.any();
export const SimilarityCheckBody = z.any();
export const SimilarityCheckResponse = z.any();
export const UpdatePatentStatusParams = z.any();
export const UpdatePatentStatusBody = z.any();
export const UpdatePatentStatusResponse = z.any();
export const ListTrademarksResponse = z.any();
export const CreateTrademarkBody = z.any();
export const GetTrademarkParams = z.any();
export const GetTrademarkResponse = z.any();
export const CheckTrademarkBody = z.any();
export const CheckTrademarkResponse = z.any();
